### ISSUE TITLE
После создания индекса не работает

### ISSUE THREAD

**Issue by dmitrystas** [MihanEntalpo/FastFuzzySearch#1]
Первый раз когда индексов нет - все нормально. Последующие запуски уже ничего не находят. Навскидку пробежался, похоже не хватает wordInfo в $indexFields
>     protected static $indexFields = array(
>         "words", "wordParts", "minPart", "maxPart", "isInitialized"
>     );
должно быть по идее так
>     protected static $indexFields = array(
>         "words", "wordParts", "wordInfo", "minPart", "maxPart", "isInitialized"
>     );

**Comment by MihanEntalpo** [comment]
Спасибо. В версии v0.2.1 я это уже поправил, но забыл сделать push и так оно и лежало у меня на компе всё это время :) Теперь всё в порядке
