### ISSUE TITLE
Ошибка в get_parts

### ISSUE THREAD

**Issue by aleksei-reznichenko** [MihanEntalpo/FastFuzzySearch#2]
[$parts[] = mb_substr($word, $i, $i + $size, "UTF-8");](https://github.com/MihanEntalpo/FastFuzzySearch/blob/master/src/FastFuzzySearch.php#L158)
нужно изменить на 
$parts[] = mb_substr($word, $i, $size, "UTF-8");
иначе размер кусочков будет в диапазоне от $min_l до $word_l

**Comment by MihanEntalpo** [comment]
Спасибо за информацию, действительно баг, который приводил к снижению точности вычисления схожести. Исправил. В версии v0.2.2 всё окей.
